### PR TITLE
Added temp_profile_warm

### PR DESCRIPTION
**Pull request by thehijacker**
Added missing MQTT topic temp_profile_warm

### CODE REVIEW

**Comment by vekexasia** [comment]
Hey, what does this do exactly?

**Comment by thehijacker** [comment]
Enabled activating profile temp_profile_warm.

**Comment by vekexasia** [comment]
Aha! didnt see that. can you please use spaces instead of tabs ? BTW nice catch.

**Comment by thehijacker** [comment]
Sure. Sorry about that. This ia actualy my first ever pull request on github. :)

**Comment by vekexasia** [comment]
Perfect THANKS

**Pull request merged**
