### PR TITLE
Add sample esphome.yaml with rate-limiting + cooling/heating season

### PR DESCRIPTION
**Pull request by medlor**
This sample would have saved me hours of debugging (mainly because the default RX/TX pins are different compared descriptions found in issues)

### CODE REVIEW

**Comment by vekexasia** [comment]
Hey, thanks for this. 

Can you please tell me why you would need rate limiting? 

Also what does winter/summer season show?

**Comment by lskuba** [comment]
You should change entities names to English

**Comment by medlor** [comment]
Hi,

just checking the logs I did see that some datapoints (like fan speed) are reported every second. Referring to https://community.home-assistant.io/t/how-to-keep-your-recorder-database-size-under-control/295795 and https://www.home-assistant.io/integrations/recorder/ it looks like it is general best practice to not send to many values.
Guys in discord agree on that and had pointed me to this rate limit configuration. My sqlite database is already very big and comfoair store by far the most datapoints.

Winter summer season are reported very seldom. Currently cooling_season is true for my machine. I found those settings here: https://github.com/adorobis/hacomfoairmqtt/blob/897b281e9455fd91075e4dd1c10d91786839af92/README.md

best regards
Tobias

**Comment by vekexasia** [comment]
Thanks @medlor 

I might put this on default in a future release so you dont need to re-define every single item with the filters

**Pull request merged**
