### PR TITLE
add analog ports

### PR DESCRIPTION
**Pull request by gekkekoe**

### CODE REVIEW

**Comment by vekexasia** [comment]
Hey @gekkekoe what are analog ports?

**Comment by gekkekoe** [comment]
it's the output of the co2 sensors for example. They output 0v-10v. 
https://www.zehnder.nl/nl/ventilatie/co2-gestuurde-ventilatie/zehnder-co2-room-sensor-0-10v

**Comment by vekexasia** [comment]
Ooh that's new. I never saw those. Wondering if there are other sensors available. Do you have other examples? Btw thanks for PR .

**Comment by svde** [comment]
I have the option box, which exposes those 4 0-10V inputs. I have a 0-10V zigbee dimmer attached to the first 0-10V input. 
image

I don't have anything attached to the 2nd port, but it's showing 25.5V, which shouldn't be possible...

When I change the output on the zigbee dimmer, I see some strange values coming by on the comfoair-esp32, like 1846.9 V.

Is it only the intention to read these 0-10V values, or will we be able to change them --> act like a CO2 sensor, etc?

**Comment by gekkekoe** [comment]
I also have an option box with 2 co2 sensors attached. I only see NA on port 3 and 4.
I also tested one of the sensors, and when it's ramping up, I do see weird values (1894.7 and -1711.2). When it's stable, I see the 0v-10v. Can't remember if I saw this with the mqtt implementation (only patched the mqtt version locally).

@vekexasia could it be that we need wait for a data available signal/flag or something before reading the data?

**Pull request merged**
